### ISSUE TITLE
Using reflective-rapidjson in bare metal Xilinx Zynq-7000

### ISSUE THREAD

**Issue by arietto** [Martchus/reflective-rapidjson#4]
Hello! I used C++/Qt and Q_GADGET PODs, QtJsonSerializer for JSON serialization in Debian. Now I have to switch to bare metal Xilinx Zynq-7000 (ARM Cortex-A9).
I'd like to have an alternative to MOC compiler for metadata (I'll switch from QVector to std::vector etc in PODs). Can your project be helpful for such hardware?

**Comment by Martchus** [comment]
It should work on every platform supported by Clang as target. If you can not compile on the platform itself, e.g. because it has not enough RAM, you obviously need to cross compile. This should generally work as I do this for targeting Windows.

I like to note that this is a one-man project and there are lots of [TODOs](https://github.com/Martchus/reflective-rapidjson#planned-features-and-todos) which I haven't been able to implement so far but which would be useful in practice. So you should really also check whether this meets your requirements feature-wise. I'd especially like to note that there's no generic reflection API like in Qt so far.

**Comment by arietto** [comment]
OK, thank you.
